### ISSUE TITLE
Uncaught (in promise) Error: spawn UNKNOWN

### ISSUE THREAD

**Issue by freeman42x** [Tehnix/ide-haskell-hie#36]
HIE does not start, instead the following error is printed in the developer console:

> Uncaught (in promise) Error: spawn UNKNOWN
>     at _errnoException (util.js:1024:11)
>     at ChildProcess.spawn (internal/child_process.js:323:11)
>     at Object.exports.spawn (child_process.js:514:9)
>     at HaskellLanguageClient.spawnServer (C:\Users\Razvan\.atom\packages\ide-haskell-hie\lib\ide-haskell-hie.js:94:36)
>     at HaskellLanguageClient.startServerProcess (C:\Users\Razvan\.atom\packages\ide-haskell-hie\lib\ide-haskell-hie.js:27:17)
>     at HaskellLanguageClient.<anonymous> (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:255:191)
>     at Generator.next (<anonymous>)
>     at C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:7:71
>     at new Promise (<anonymous>)
>     at __awaiter (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:3:12)
>     at process.reportBusyWhile (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:255:132)
>     at HaskellLanguageClient.<anonymous> (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:56:29)
>     at Generator.next (<anonymous>)
>     at C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:7:71
>     at new Promise (<anonymous>)
>     at __awaiter (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:3:12)
>     at HaskellLanguageClient.AutoLanguageClient.reportBusyWhileDefault (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:52:53)
>     at HaskellLanguageClient.<anonymous> (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:49:29)
>     at Generator.next (<anonymous>)
>     at C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:7:71
>     at new Promise (<anonymous>)
>     at __awaiter (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:3:12)
>     at HaskellLanguageClient.AutoLanguageClient.reportBusyWhile (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:44:46)
>     at HaskellLanguageClient.<anonymous> (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:255:40)
>     at Generator.next (<anonymous>)
>     at C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:7:71
>     at new Promise (<anonymous>)
>     at __awaiter (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:3:12)
>     at HaskellLanguageClient.startServer (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:254:16)
>     at ServerManager._serverManager.server_manager_js_1.ServerManager [as _startServer] (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:220:81)
> util.js:1024 Uncaught (in promise) Error: spawn UNKNOWN
>     at _errnoException (util.js:1024:11)
>     at ChildProcess.spawn (internal/child_process.js:323:11)
>     at Object.exports.spawn (child_process.js:514:9)
>     at HaskellLanguageClient.spawnServer (C:\Users\Razvan\.atom\packages\ide-haskell-hie\lib\ide-haskell-hie.js:94:36)
>     at HaskellLanguageClient.startServerProcess (C:\Users\Razvan\.atom\packages\ide-haskell-hie\lib\ide-haskell-hie.js:27:17)
>     at HaskellLanguageClient.<anonymous> (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:255:191)
>     at Generator.next (<anonymous>)
>     at C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:7:71
>     at new Promise (<anonymous>)
>     at __awaiter (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:3:12)
>     at process.reportBusyWhile (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:255:132)
>     at HaskellLanguageClient.<anonymous> (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:56:29)
>     at Generator.next (<anonymous>)
>     at C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:7:71
>     at new Promise (<anonymous>)
>     at __awaiter (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:3:12)
>     at HaskellLanguageClient.AutoLanguageClient.reportBusyWhileDefault (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:52:53)
>     at HaskellLanguageClient.<anonymous> (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:49:29)
>     at Generator.next (<anonymous>)
>     at C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:7:71
>     at new Promise (<anonymous>)
>     at __awaiter (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:3:12)
>     at HaskellLanguageClient.AutoLanguageClient.reportBusyWhile (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:44:46)
>     at HaskellLanguageClient.<anonymous> (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:255:40)
>     at Generator.next (<anonymous>)
>     at C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:7:71
>     at new Promise (<anonymous>)
>     at __awaiter (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:3:12)
>     at HaskellLanguageClient.startServer (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:254:16)
>     at ServerManager._serverManager.server_manager_js_1.ServerManager [as _startServer] (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:220:81)
> util.js:1024 Uncaught (in promise) Error: spawn UNKNOWN
>     at _errnoException (util.js:1024:11)
>     at ChildProcess.spawn (internal/child_process.js:323:11)
>     at Object.exports.spawn (child_process.js:514:9)
>     at HaskellLanguageClient.spawnServer (C:\Users\Razvan\.atom\packages\ide-haskell-hie\lib\ide-haskell-hie.js:94:36)
>     at HaskellLanguageClient.startServerProcess (C:\Users\Razvan\.atom\packages\ide-haskell-hie\lib\ide-haskell-hie.js:27:17)
>     at HaskellLanguageClient.<anonymous> (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:255:191)
>     at Generator.next (<anonymous>)
>     at C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:7:71
>     at new Promise (<anonymous>)
>     at __awaiter (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:3:12)
>     at process.reportBusyWhile (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:255:132)
>     at HaskellLanguageClient.<anonymous> (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:56:29)
>     at Generator.next (<anonymous>)
>     at C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:7:71
>     at new Promise (<anonymous>)
>     at __awaiter (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:3:12)
>     at HaskellLanguageClient.AutoLanguageClient.reportBusyWhileDefault (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:52:53)
>     at HaskellLanguageClient.<anonymous> (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:49:29)
>     at Generator.next (<anonymous>)
>     at C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:7:71
>     at new Promise (<anonymous>)
>     at __awaiter (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:3:12)
>     at HaskellLanguageClient.AutoLanguageClient.reportBusyWhile (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:44:46)
>     at HaskellLanguageClient.<anonymous> (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:255:40)
>     at Generator.next (<anonymous>)
>     at C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:7:71
>     at new Promise (<anonymous>)
>     at __awaiter (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:3:12)
>     at HaskellLanguageClient.startServer (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:254:16)
>     at ServerManager._serverManager.server_manager_js_1.ServerManager [as _startServer] (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:220:81)
> util.js:1024 Uncaught (in promise) Error: spawn UNKNOWN
>     at _errnoException (util.js:1024:11)
>     at ChildProcess.spawn (internal/child_process.js:323:11)
>     at Object.exports.spawn (child_process.js:514:9)
>     at HaskellLanguageClient.spawnServer (C:\Users\Razvan\.atom\packages\ide-haskell-hie\lib\ide-haskell-hie.js:94:36)
>     at HaskellLanguageClient.startServerProcess (C:\Users\Razvan\.atom\packages\ide-haskell-hie\lib\ide-haskell-hie.js:27:17)
>     at HaskellLanguageClient.<anonymous> (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:255:191)
>     at Generator.next (<anonymous>)
>     at C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:7:71
>     at new Promise (<anonymous>)
>     at __awaiter (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:3:12)
>     at process.reportBusyWhile (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:255:132)
>     at HaskellLanguageClient.<anonymous> (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:56:29)
>     at Generator.next (<anonymous>)
>     at C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:7:71
>     at new Promise (<anonymous>)
>     at __awaiter (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:3:12)
>     at HaskellLanguageClient.AutoLanguageClient.reportBusyWhileDefault (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:52:53)
>     at HaskellLanguageClient.<anonymous> (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:49:29)
>     at Generator.next (<anonymous>)
>     at C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:7:71
>     at new Promise (<anonymous>)
>     at __awaiter (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:3:12)
>     at HaskellLanguageClient.AutoLanguageClient.reportBusyWhile (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:44:46)
>     at HaskellLanguageClient.<anonymous> (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:255:40)
>     at Generator.next (<anonymous>)
>     at C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:7:71
>     at new Promise (<anonymous>)
>     at __awaiter (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:3:12)
>     at HaskellLanguageClient.startServer (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:254:16)
>     at ServerManager._serverManager.server_manager_js_1.ServerManager [as _startServer] (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:220:81)

I am using HIE on Windows set up with the wrapper powershell script.
HIE version: Version 0.4.0.1, Git revision 7e0b19721872d1c8e44f49484ac75f6c61412349 (2220 commits) x86_64 ghc-8.4.4

**Comment by patrickaldis** [comment]
Hi, did you find a solution to this? Am having the same problem.

**Comment by freeman42x** [comment]
@patrickaldis See: https://github.com/Tehnix/ide-haskell-hie/issues/38
