### ISSUE TITLE
Complete unresponsiveness

### ISSUE THREAD

**Issue by sniperrifle2004** [Tehnix/ide-haskell-hie#5]
I am trying to get ide-haskell-hie 0.7.2 to work, but all information requests appear to be hanging. It does manage to detect capabilities and I can issue requests using atom-ide-ui. The only thing I am getting is uninformative errors from what-the-status., which could be related, but due to the lack of information this is inconclusive:

```
Uncaught (in promise) TypeError: Cannot read property '9' of null
    at parseRenamedOrCopiedEntry (/usr/lib/atom/node_modules/what-the-status/index.js:154:20)
    at parseLine (/usr/lib/atom/node_modules/what-the-status/index.js:67:19)
    at Stream.<anonymous> (/usr/lib/atom/node_modules/what-the-status/index.js:36:31)
    at emitOne (events.js:96:13)
    at Stream.emit (events.js:188:7)
    at drain (/usr/lib/atom/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/usr/lib/atom/node_modules/through/index.js:45:5)
    at emit (/usr/lib/atom/node_modules/split/index.js:37:14)
    at next (/usr/lib/atom/node_modules/split/index.js:49:7)
    at Stream.<anonymous> (/usr/lib/atom/node_modules/split/index.js:54:5)
    at Stream.stream.write (/usr/lib/atom/node_modules/through/index.js:26:11)
    at Readable.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Readable.emit (events.js:188:7)
    at Readable.read (_stream_readable.js:381:10)
    at flow (_stream_readable.js:761:34)
    at emitReadable_ (_stream_readable.js:433:3)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

I have literally no idea what happens with hie, other than that it IS started. 

I would like to investigate further, but I have no idea where and how to start.

I am running atom 1.22.1 on archlinux, in a lts-9.17 stack project, with hie 0.1.0.0 (701723324eef5101a0c1bbcfac0d58d6ffaaaef0) from git

**Comment by sniperrifle2004** [comment]
Through a combination of core.debugLSP and using a modified version of ide-haskell-ide I figured out that the requests arrive at hie, but no response returns. So the problem lies there.

**Comment by sniperrifle2004** [comment]
For others stumbling on this, I was experiencing an instance of this issue: https://github.com/haskell/haskell-ide-engine/issues/400
